### ISSUE TITLE
[Meta] Cover step 4 (Docker image tagging and pushing)

### ISSUE THREAD

**Issue by vdice** [deis/deisrel#58]
The outcome of this work should be a deisrel command that replaces the use of deis-workflow-group as seen in http://docs-v2.readthedocs.io/en/latest/roadmap/release-checklist/#step-4-tag-and-push-docker-images

TODO:
- [ ] command for ~~docker tagging~~ checking docker tags https://github.com/deis/deisrel/issues/6
- [ ] command for docker pushing https://github.com/deis/deisrel/issues/57
- [ ] update https://github.com/deis/workflow/blob/master/src/roadmap/release-checklist.md

**Comment by vdice** [comment]
This meta ticket is not going to make the `rc1` milestone, pushing to `v2.0`
